### ISSUE TITLE
TLD function: Check SpamHaus for top spam domains?

### ISSUE THREAD

**Issue by CyanoTex** [hjk789/NXEnhanced#1]
NextDNS ATM doesn't check SpamHaus for the top 10 spam domains. Is it possible to add this to the script?

**Comment by hjk789** [comment]
You mean to add a feature that gets from SpamHaus' DNSBL an updated list of the 10 most abused TLDs?

**Comment by CyanoTex** [comment]
> You mean to add a feature that gets from SpamHaus' DNSBL an updated list of the 10 most abused TLDs?

That's the gist of it. Is that possible?

**Comment by hjk789** [comment]
It's possible, but I'm not sure it's feasible. I'll take a closer look into this, and I'll tell you whether that can be added. No guarantees though.

**Comment by hjk789** [comment]
This won't be added, it's too out of scope.
