### ISSUE TITLE
Real-time log

### ISSUE THREAD

**Issue by hjk789** [hjk789/NXEnhanced#14]

**Comment by quantumpacket** [comment]
NextDNS now has a auto-refresh button that will show logs in real-time as they are logged. If this was what you intended to implement, then this can be closed.

**Comment by hjk789** [comment]
Yeah, but there's no filtering or buttons in the new entries, you have to click the refresh button to reload the logs to make them appear again. So either NXE has to be adapted to go back relying on what is shown on each new log entry loaded by the site, or implement NXE's own real-time log feature, which was the original intention. It would work the same way as the official implementation, by polling for new logs each second or more. So it would be apparently easy to implement and wouldn't make any noticeable difference.

**Comment by hjk789** [comment]
This feature is now implemented in the Firefox extension. Maybe I might implement this on the userscript too.
