### ISSUE TITLE
Log filtering control is hidden behind the log

### ISSUE THREAD

**Issue by bpjones** [hjk789/NXEnhanced#24]
Bug:  The log filtering controls are hidden behind the log itself when viewed on a 13" Macbook Pro at native resolution.

![Screen Shot 2021-03-03 at 12 42 23 PM](https://user-images.githubusercontent.com/554791/109856308-f5d25f00-7c1e-11eb-8c10-aab466d3b9e7.png)

**Comment by hjk789** [comment]
Is the window narrowed? I just tested here with a narrowed window and it's happening here too. This happens because the filtering controls are just using the empty space on the right instead of actually occupying the space. I'm working on a fix, thanks for the feedback!

**Comment by bpjones** [comment]
Thanks for the fix!!  In case this helps, with Firefox completely maximized, running in full screen mode at native resolution on the 13" Intel MBP, Firefox sees the screen resolution as 1440 x 900 pixels.

**Comment by hjk789** [comment]
I released version 4.4 with the fix. Can you update it and test whether the bug still occurs?

**Comment by bpjones** [comment]
It’s fixed!  Thanks for the incredibly fast response!!

**Comment by hjk789** [comment]
Nice! Feel free for other feedback you might come to have. :)
