### ISSUE TITLE
Page is not refreshed when switching config

### ISSUE THREAD

**Issue by CamilleGuillory** [hjk789/NXEnhanced#27]
When I am on the log section, switching the configuration does not refresh the page.
I have to force a refresh to display the correct logs.

**Comment by hjk789** [comment]
Thanks for the feedback! The fix will come in the next update.

**Comment by hjk789** [comment]
The new version is now released. Can you update and test if it's still happening?

**Comment by CamilleGuillory** [comment]
It works perfectly now.
Thank you !
