### ISSUE TITLE
Allow/Deny button not showing correctly

### ISSUE THREAD

**Issue by katchy3132** [hjk789/NXEnhanced#3]
the popup for the Allow/Deny button is not showing correctly in my Chrome instance

![image](https://user-images.githubusercontent.com/3707138/87943609-f27ece80-caa6-11ea-8032-e9bb3ad9f940.png)

I think I have uBlock Origin set correctly : 
 
![image](https://user-images.githubusercontent.com/3707138/87943731-1f32e600-caa7-11ea-93b3-3f0ae48d4679.png)

is there something else I can tweak?

great script!

**Comment by hjk789** [comment]
Your uBlock is configured correctly. I tested here and this specific problem is not happening here, but I noticed that the script is working very poorly on Chrome with TamperMonkey, while in Firefox with GreaseMonkey it's working fine. I did some testings before, but didn't tested in depth in Chrome. I'll make some tweaks to see if it works better.  
For this bug you're facing, try to refresh the page. If this doesn't work, then you'll have to wait for the fix.

**Comment by katchy3132** [comment]
refresh doesn't do anything. guess I'll wait...

**Comment by hjk789** [comment]
@katchy3132 I just released a new version with several fixes and improvements. Could you update the userscript and check if this is still happening?

**Comment by katchy3132** [comment]
Definitely an improvement. I click "Allow" then the space key but it is hanging on "Submitting..." and the domain doesnt show up in Allowlist.

**Comment by hjk789** [comment]
For some reason it's not detecting you are using Chrome. Are  you using a user-agent spoofer? In Chrome, hit Ctrl+Shift+J, paste and run the following code: `navigator.userAgent`. What does it show?
Also, open your script manager and edit NX Enhanced. In line 18, remove `!navigator.userAgent.includes("KHTML")` and replace it with `window.chrome == null`, save and go to NextDNS logs. Is it working now?

**Comment by katchy3132** [comment]
```
navigator.userAgent
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
```
the change in line 18 makes it work. thanks.

**Comment by hjk789** [comment]
Nice. I'll release an update with this change. This other method is more reliable to detect Chrome.
