### ISSUE TITLE
Syntax Errors NXEnhanced.js 

### ISSUE THREAD

**Issue by vrysmart** [hjk789/NXEnhanced#35]
Uncaught SyntaxErrors: 
ExportConfigButton.onclick
Unexpected end of JSON input
    at JSON.parse 
(anonymous) line 1734

load (async) 
 makeApiRequest
at XMLHttpRequest.xhr.onload line 2347

Caught by browser debugger as spinner never stopped.

**Comment by hjk789** [comment]
Thanks for the feedback. I just need more info to be able to find the cause of the problem. 

- What browser were you using when this happened?
- Do you use any behavior blocking extensions on this browser?
- Did you made any customizations to your browser which restricts how it works?
- You were trying to export your config, right? In the Logs page, are the logs loading or it just keeps spinning?
- Even if you refresh the page, this problem always happens?
- Is this related to #36 or is this another problem? Were you trying to do the same thing?

**Comment by hjk789** [comment]
Closed after one week without response.
