### ISSUE TITLE
Youtube ads and Settings

### ISSUE THREAD

**Issue by denrusvrn** [hjk789/NXEnhanced#42]
I welcome you!Is it possible to somehow implement this in your script to block ads on YouTube?And now there are already ready-made files https://gist.github.com/rtfpessoa/7fdd3d4121ee4acafe56e8425154888a , take a look or tell me how to add it in the browser so that everything is saved when using it works?And when 250 thousand requests are reached, a sign pops up that it is approaching 300 thousand requests and the log tab does not fully work, namely, part of your settings disappears, like this...Thank you in advance and thank you for your understanding!

**Comment by hjk789** [comment]
You mean to add the ability of importing domain lists from the internet? Although it's totally possible to implement this, both NextDNS' API and website are not suited for this, also people would link to huge lists with hundreds of thousands of domains, which would take forever to finish, would overload the server and would make the denylist extremely heavy. Also, it would face the same problem as #41.  

If you want to remove YouTube ads, just use uBlock Origin.

> And when 250 thousand requests are reached, a sign pops up that it is approaching 300 thousand requests    

This could be implemented as an option. When the billable query count reaches above 250,000, the next time the user goes to the NextDNS site a message would appear noting that the limit is almost reached.

> the log tab does not fully work, namely, part of your settings disappears

Can you post a screenshot?

**Comment by quantumpacket** [comment]
> This could be implemented as an option. When the billable query count reaches above 250,000, the next time the user goes to the NextDNS site a message would appear noting that the limit is almost reached.

I thought this was already a thing NextDNS does, where it displays a notice at the top of dashboard that you are nearing your quota limit.

**Comment by hjk789** [comment]
Oh, it is? I didn't know, I never reached the limit after they implemented the billable queries count. So never mind.

**Comment by hjk789** [comment]
> the log tab does not fully work, namely, part of your settings disappears

@denrusvrn  Can you post a screenshot?

**Comment by hjk789** [comment]
Closed after over one week without response.
