### ISSUE TITLE
Firefox Addon - Sort Options Broken

### ISSUE THREAD

**Issue by quantumpacket** [hjk789/NXEnhanced#44]
Neither 4.7.1 or 4.7.10 seem to work under Firefox 78.15.0esr. I get the following error when I attempt to toggle any of the sort options and CPU spikes to 25% for that Firefox tab. In addition, current selected options from saved settings are not being applied on page load.

![Screenshot_2021-10-25_11-06-51](https://user-images.githubusercontent.com/8516784/138721341-a71d19ce-f56e-4406-bc6d-2adb1bd7a774.png)

**Comment by hjk789** [comment]
I tried to reproduce the problem on Firefox 93 but it worked fine. It's either a problem on Firefox 78.15.0esr or a specific domain that is causing the extension to misbehave. Does this started to happen recently or it was already happening in older versions of NXE? If you create a new config and add some domains, does it still happen?

**Comment by quantumpacket** [comment]
@hjk789 Figured out the cause. If I add a TLD to the list it causes the issue. So adding `*.fr` for example will do it.

**Comment by hjk789** [comment]
I suspected it was something like that. The sorting algorithm is not expecting TLDs, and for some reason it's causing an infinite loop when parsing it. I'll investigate a fix. In the mean time, remove all TLDs from the list and add them in the TLDs list in the Security page instead.
