### ISSUE TITLE
[Firefox] Import settings broken

### ISSUE THREAD

**Issue by dalisoft** [hjk789/NXEnhanced#48]
- Waiting and nothing is happening at UI side
- Something got wrong in logic/code (DevMode error)

<img width="1392" alt="Screenshot 2022-01-05 at 14 03 00" src="https://user-images.githubusercontent.com/3511344/148190358-006d0bc9-2e02-4adc-9f89-55e88d7b8d58.png">

**Comment by hjk789** [comment]
Did you modify the file to be imported? Currently you can't do partial imports, you can only import a complete settings file. A partial import is planned (#31).

Also, please note that the file to be imported must follow the same structure as the exported file.

**Comment by dalisoft** [comment]
I just imported the exported file and got that error

**Comment by hjk789** [comment]
I tested here in both Firefox and Chrome and it imported fine. 

The error you are seeing says that the `settings` property is missing in the file you are importing. Are you sure you are importing the right file? The blue buttons are for exporting/importing the NextDNS config, while the gray buttons are for exporting/importing the NX Enhanced settings only.

When you import is there any activity in the Network tab?

**Comment by hjk789** [comment]
Closed after one week without response.

**Comment by dalisoft** [comment]
@hjk789 Sorry for delaying, it's working for exports fine, currently i am writing own parser to get both AdBlock and Hosts compatible results from export of your plug-in, you doing nice job. As soon as finish my code, i'll publish to GitHub and let you know if you wish integrate.
AdBlock compatible rules gives possibility to export rules from NextDNS to many blockers like AdGuardDNS, uBlock Origin, etc

**Comment by hjk789** [comment]
Sure, I'll take a look when done.

**Comment by dalisoft** [comment]
Hi @hjk789 

My script is done, look at https://github.com/dalisoft/dns-helper

**Comment by hjk789** [comment]
Nice. What is the integration you thought of for NX Enhanced?

**Comment by dalisoft** [comment]
It handles the output of NXEnhanced NextDNS config and gives result of hosts or rules formatted file
