### ISSUE TITLE
Option to filter the logs by "blocked reason" :)

### ISSUE THREAD

**Issue by AC9864** [hjk789/NXEnhanced#50]
I have any idea about this new feature, the ability to filter the logs by blocked reason, e.g., we can filter the logs page, and it shows logs that are blocked a specified blocked reason, like OSID / steven black / AI Security... etc. You get the point, right? 

- By the way, thank you so much for your time and efforts in making the extensions! I highly appreciate your efforts:]

**Comment by hjk789** [comment]
Thanks for your suggestion! I think this was already proposed in the issue #20, but it was only blocklists. I'll expand it to any block reason instead of just blocklists. :)

**Comment by AC9864** [comment]
Huge thanks for your reply! By the way, if possible, I would like to filter the logs by IP address as well!

**Comment by hjk789** [comment]
I could add that ability in the search bar, in which you would type something like `ip:123.123.123.123` and it would only list the IP you specified.

**Comment by AC9864** [comment]
> I could add that ability in the search bar, in which you would type something like `ip:123.123.123.123` and it would only list the IP you specified.

That's great! Thanks!
