### ISSUE TITLE
"Contribute Now" button link error on Paypal

### ISSUE THREAD

**Issue by celtea** [hjk789/NXEnhanced#55]
Clicking the "Contribute Now" on the Firefox Extensions page [https://addons.mozilla.org/en-US/firefox/addon/nx-enhanced/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search](url) takes user to a Paypal page that shows the message "PayPal  cannot process this transaction because of a problem with the seller's  website. Please contact the seller directly to resolve this problem."

<img width="789" alt="Screen Shot 2022-04-18 at 5 44 02 AM" src="https://user-images.githubusercontent.com/25175581/163790612-fee11b72-0cc6-4d45-a045-ac8bb79a9f9a.png">

**Comment by hjk789** [comment]
Thanks for pointing that out, I forgot to update that one. It's fixed now.
