### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by bubobih** [hjk789/NXEnhanced#58]
Extension on chrome stopped working on some pages... example on logs page he just load indefinitly

https://i.imgur.com/YyzxhXo.png

**Comment by chessmck** [comment]
I noticed the same.  Had to turn this add-in off in both Chrome and Firefox to access nextDNS logs.

**Comment by hjk789** [comment]
Thanks for the feedback. They did some changes in the API. I'll fix it as soon as possible.

---
Correction: they did **a lot** of changes to the API, they restructured the responses, changed names, etc., it will take much more time than I expected to fix it.

**Comment by smell-my-finger** [comment]
Thanks for maintaining this project. After log activity is restored, can you look into the option of showing only _allowed_ connections? I scroll my logs looking for new/oddball connections to block, and omitting red ones that are already blocked would be immensely helpful.

**Comment by hjk789** [comment]
@smell-my-finger 
> can you look into the option of showing only _allowed_ connections?

Sure, I was also thinking on that feature for quite some time. What you can do for now is adding these blocked domains to the filter, this way your logs won't get cluttered by them.

**Comment by hjk789** [comment]
**Update**: Now I understand what happened: NextDNS created a new, separated API, and made it public since some months ago, but the website was using the original API, and what they did now was making the website use the new API. That's why so many things were changed, because it's not the same API.

**Comment by dooley74** [comment]
still broken?

**Comment by hjk789** [comment]
@dooley74 It's not finished yet, it was GitHub who closed the issue automatically by mistake.

**Comment by dooley74** [comment]
@hjk789 still getting the blue idle circle on Brave and Firefox when trying to load the logs page.
Removed the extension from both. Cleared cache, rebooted then reinstalled following links from github.

**Comment by hjk789** [comment]
@dooley74 I didn't released the update yet. If you want to test it before release, just download the WebExtension directory and install in your browser the unpacked extension.

**Comment by dooley74** [comment]
> @dooley74 I didn't released the update yet. If you want to test it before release, just download the WebExtension directory and install in your browser the unpacked extension. I just need to do some more tests and likely today or tomorrow the fixes will be released.

I've tried installing the extension manually in Brave Browser, but get the following error when doing so. The same error is shown in the standard Chrome browser as well.
Any suggestions?
![image](https://user-images.githubusercontent.com/29153847/178859812-fb652b6a-3bd0-4a69-beba-0d34db47f4e2.png)

**Comment by hjk789** [comment]
@dooley74  You didn't download the directory, you downloaded the page. Try [this link](https://github.com/hjk789/NXEnhanced/archive/refs/heads/master.zip). Extract the zip and load the extracted WebExtension folder.

**Comment by RouterCFW** [comment]
Will the Userscript be updated as well since I’m on iOS and can’t use the chrome extension

**Comment by hjk789** [comment]
@RouterCFW Maybe. I was thinking in releasing a "definitive update" to the userscript for quite some time.

**Comment by RouterCFW** [comment]
Please do since it’s the only way I can use it 😅

**Comment by hjk789** [comment]
The update is now released.

If anyone encounter any problem, please let me know.

**Comment by Lippiece** [comment]
@hjk789 
Hi, I'm still encountering this issue even after script reinstallation. 

[my.nextdns.io-1661628141076.log](https://github.com/hjk789/NXEnhanced/files/9438549/my.nextdns.io-1661628141076.log)

The Chrome addon works fine.

**Comment by hjk789** [comment]
@Lippiece I didn't fix the userscript yet, and you shouldn't expect that to happen anytime soon, as the userscript is discontinued. I do intend not only fixing the userscript but also upgrading it, but that's not on my priorities. If you really need the userscript, [I'm always open for donations](https://github.com/hjk789/NXEnhanced/wiki/Donation-methods).
