### ISSUE TITLE
Denylist stuck on loading wheel when trying to add multiple URLs

### ISSUE THREAD

**Issue by Gigafrost** [hjk789/NXEnhanced#60]
I don't know if this has been reported before and I apologize if it has, but it looks like when trying to add multiple URLs in the Deny List it doesn't work. It just hangs on the loading wheel and doesn't add any domains. Any idea on what could be going on? Thanks!

**Comment by hjk789** [comment]
https://github.com/hjk789/NXEnhanced/issues/58

**Comment by jmcglock** [comment]
I am still experiencing this issue. Using Chrome extension. I assume changes committed to master are reflected in the latest version of the chrome extension but I could be wrong. Please advise.

**Comment by hjk789** [comment]
A new version with the fix has been released. Please make sure to update it.
