### ISSUE TITLE
Adding all TLDs does not work

### ISSUE THREAD

**Issue by Quorum75** [hjk789/NXEnhanced#62]
Somehow all TLDs are not added. Most added are the asian and arabic ones. 

I tried several times but it didin't work. For instance I had to manually add .ru to the list.

Firefox 102.0.1 (64-bit)
macOS 12.4 (21F79)

**Comment by hjk789** [comment]
#58

**Comment by Quorum75** [comment]
Hum... This is a totally different issue. I don't see the relationship with the loading problem on Chrome.

**Comment by hjk789** [comment]
The issues are different, but both are caused by the same problem, which is discussed there.

**Comment by Quorum75** [comment]
Thanks for the response.
How will we know when the fix will be roll out?

**Comment by hjk789** [comment]
A new version with the fix has been released. Please make sure to update it.

**Comment by Quorum75** [comment]
There is no new update when checking. 
The last one is from July 18th. 

Finally found the solution. Default update doesn't work. I had to switch to On. Weird...

By the way, a Delete all would be nice to go back from scratch ;)
