### ISSUE TITLE
"Export this config" not working

### ISSUE THREAD

**Issue by Quorum75** [hjk789/NXEnhanced#63]
Exporting this config does not work. The wheel spins non stop. Only the export of NXE settings worked.

Firefox 102.0.1 (64-bit)
macOS 12.4 (21F79)

**Comment by hjk789** [comment]
#58

**Comment by Quorum75** [comment]
Thanks I saw it but it was Chrome and I was on Firefox so I wasn't sure. Cheers

**Comment by hjk789** [comment]
Both browsers work very similarly, the problem was caused by a change in the NextDNS API, which broke NXE.

**Comment by looeee** [comment]
This is the error on Chrome. 

![nextdns export error](https://user-images.githubusercontent.com/5307958/183247241-26834a0f-0b4a-4558-9b36-3667c99d21e7.png)

**Comment by Quorum75** [comment]
Thanks
