### ISSUE TITLE
Right-Alignment Causes Icon To Be On Its Own Line

### ISSUE THREAD

**Issue by quantumpacket** [hjk789/NXEnhanced#64]
Using the latest release, when right alignment is used the icons move to their own line.

![Screenshot_2022-08-20_12-18-06](https://user-images.githubusercontent.com/8516784/185756859-61947f56-eb19-4340-87f4-7989e1f81f7b.png)

The icon has `display: block` applied to it, which would make it take up all horizontal space within the parent element. Changing to `display: inline-block` appeared to fix it for me.

A big thank you for your hard work getting the new release out. NextDNS needs to hire you!

**Comment by hjk789** [comment]
Thanks for the feedback. This problem was also happening in the logs, and did the fix. Didn't noticed it was also happening in the allow/denylist.
The fix will come in the next release.

>A big thank you for your hard work getting the new release out. NextDNS needs to hire you!

Thanks! I'll take that as a compliment, but I'm sure they have no intention in doing that.
