### ISSUE TITLE
Device select dropdown in logs page does not have option for "Unidentified devices" resulting in incorrect device filter being applied

### ISSUE THREAD

**Issue by iAmMrinal0** [hjk789/NXEnhanced#69]
Screenshot without the extension on Firefox version: 107.0
![image](https://user-images.githubusercontent.com/890062/204503959-7d75ca68-972f-41d3-a32c-7c95df0f4d37.png)

So when this option isn't shown, selecting a device doesn't show the logs for that device. It shows it for the previous device in the dropdown list.

**Comment by hjk789** [comment]
"Unidentified devices" and "Other devices" are the same thing. Maybe I could rename it to the official name.

**Comment by iAmMrinal0** [comment]
@hjk789 that's right. It's a mistake on my part. I assumed that the issue is caused by not showing the option. The underlying issue is that selecting the device results in logs for the device above it. For example, refer to this screenshot where device selected is `x` and logs for device `y` are shown

![image](https://user-images.githubusercontent.com/890062/204977487-04b1a10f-46c2-4029-acf0-c08a780ee0bb.png)

I would expect logs of `risa` to show up but it shows logs for device `betazed` which is the device above `risa` in the list.

![image](https://user-images.githubusercontent.com/890062/204977795-c774b33a-6656-4dee-877f-18be8ce37ef1.png)

I tried the extension on Chrome too and it's the same behavior. Let me know if there's any more information I could provide.

**Comment by hjk789** [comment]
I tested here and the problem you're reporting is not happening for me. I'll try doing a more in-depth test and I'll update you when done.

**Comment by hjk789** [comment]
@iAmMrinal0 I just published a new release that fixes the problem you reported on your last comment. Can you update and test if it's still happening?
