### ISSUE TITLE
Device list on log list incomplete

### ISSUE THREAD

**Issue by AJolly** [hjk789/NXEnhanced#70]
NX Enhanced seems to only show a partial list of devices on the log page.  

What I see without NX Enhanced:
![image](https://user-images.githubusercontent.com/91493/219889120-1bfc1073-4646-4e63-ba65-4e9575b7b32e.png)

w/NX Enhanced:  
![image](https://user-images.githubusercontent.com/91493/219889350-48cdccaa-32f1-4cf0-9bdd-5647da8c7eb4.png)

**Comment by hjk789** [comment]
Thanks for the feedback, I'll take a look.

**Comment by hjk789** [comment]
I just published a new release that likely fixes that problem. Can you update and test it to confirm whether it's fixed?

**Comment by hjk789** [comment]
Closed after a week without response.
