### ISSUE TITLE
BUG - Display issue with logs in NXEnhance when multiple devices are connected

### ISSUE THREAD

**Issue by Higor-Matos** [hjk789/NXEnhanced#71]
I have found a problem with NXEnhance related to the display of logs. When I have many devices connected, the logs display is compromised, as can be seen in the attached vídeo.

https://user-images.githubusercontent.com/54960146/223122414-601aa211-68ff-4ce6-8bb4-a8560f29b0b5.mp4

However, I noticed that when I deactivate NXEnhance, the logs are displayed correctly.

I am available to collaborate in solving this problem.

**Comment by hjk789** [comment]
Thanks for the feedback. NXE seems to be getting the wrong index for some reason, but this seems to happen only on long device lists. I'm kinda busy lately and I might take longer to take a look at this. If you'd like to contribute with code, feel free.

**Comment by Wraiith32** [comment]
I have 4 devices in mine and have the issue so I do not think it is a long list issue.

**Comment by hjk789** [comment]
@Wraiith32  I have 3 devices and it's not happening at all. Maybe 4 is the magic number? I'll test adding one more device.

**Comment by Wraiith32** [comment]
I created a pull request that should resolve the issue. https://github.com/hjk789/NXEnhanced/pull/72.  I do not think the index-1 is needed.

**Comment by hjk789** [comment]
When I've put the -1 there it *was* needed. Maybe something changed server side, which made it not needed anymore.

**Comment by hjk789** [comment]
@Higor-Matos I tested it with 9 devices, just like in your example, but it still worked fine. It was only when I added an unnamed device that the bug occurred. NXE was not considering unnamed devices in the list, that's why the index was wrong. It's fixed now., I'll release it soon.

@Wraiith32 I reverted your change as the fix didn't involve the decrement.

**Comment by Higor-Matos** [comment]
Excellent, thank you very much! I'll buy you a coffee!

**Comment by hjk789** [comment]
The version with the fix is now released!
