### ISSUE TITLE
Adding multiple domains to deny/allow list not working for me

### ISSUE THREAD

**Issue by ghost** [hjk789/NXEnhanced#75]
I tried three different browsers but turning the option on does not change anything. The extension seems to be enabled because I can see the buttons on the logs tab.

**Comment by hjk789** [comment]
Tested here and it's working fine. Are you using the latest version of the extension?

**Comment by ghost** [comment]
I'm using version 5.1. Tried updating Chrome as well.

**Comment by ghost** [comment]
Now tried it on Firefox and it's not saving my settings. I don't know what's going on.

**Comment by hjk789** [comment]
That's weird, I really can't reproduce the problem. It's working fine in both Firefox and Chrome here, so the problem is on your end, I just don't know what. Maybe it's another extension that is causing this? Or you have a faulty system? 

Which features are working?

**Comment by ghost** [comment]
I don't know, I did a fresh install of a Chromium-based browser on my phone, and same problem - both on wifi and mobile data. I was only able to verify that the buttons in the logs section were present. I guess there is nothing we can do about it.

**Comment by hjk789** [comment]
Is your allowlist/denylist empty? Currently the features aren't added to the page when the list is empty. Try adding a test domain to the list and check if the features appear. I need to fix that.

**Comment by ghost** [comment]
I actually tried that but now I tried again and it works. Thank you!
